'use strict';
const {Game,CONFIG}=BugHunter;
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let game=new Game(),state='ready',last=0,accumulator=0,w=800,h=350,noticeUntil=0,round=0;
const tasks=['Сделать форму логина','Починить корзину','Добавить экспорт в PDF'];
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;game.setFieldWidth(w);const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw();}
function feedback(text){$('feedback').textContent=text;noticeUntil=game.time+2.5;}
function hud(){const seconds=Math.max(0,Math.ceil(CONFIG.duration-game.time));$('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('features').textContent=game.delivered;$('progress').style.width=Math.min(100,game.delivered/14*100)+'%';$('bugs').textContent=Object.values(game.missed).reduce((a,b)=>a+b,0);$('timer').style.color=game.time>=55?'#bf453b':'';}
function start(){if(state==='paused'){state='playing';}else{game=new Game(Math.random,w);round++;state='playing';$('task').textContent='Задача: '+tasks[(round-1)%tasks.length];feedback('Жди жука в фиолетовой зоне — и бей!');}last=0;accumulator=0;$('overlay').hidden=true;$('hit').disabled=false;$('pause').disabled=false;hud();}
function pause(){if(state!=='playing')return;state='paused';$('hit').disabled=true;$('pause').disabled=true;show('ПЕРЕРЫВ НА ЧАЙ','Прод подождёт.','<p>Спринт на паузе. Вернись, когда будешь готова.</p>','Продолжить');}
function show(tag,title,body,button){$('card-tag').textContent=tag;$('card-title').textContent=title;$('card-body').innerHTML=body;$('start').textContent=button;$('overlay').hidden=false;}
function finish(){state='finished';$('hit').disabled=true;$('pause').disabled=true;const v=game.verdict();show('ИТОГИ СПРИНТА',v.title,`<p>${v.text}</p><div class="result-grid"><span><b>${game.delivered}/20</b>фич в релизе</span><span><b>${game.lost}</b>фич потеряно</span><span><b>${game.fixed}</b>багов исправлено</span></div><p>В проде: 🔴 ${game.missed.critical} · 🔵 ${game.missed.medium} · 🟢 ${game.missed.minor}</p><p class="muted">Лучшая серия: ${game.bestCombo} · Возвратов: ${game.returned}</p>`,'Ещё один спринт ↗');feedback('Проверка завершена. Результат перед тобой.');}
function strike(){if(state==='playing')game.strike();}
$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);for(const surface of [$('hit'),canvas])surface.addEventListener('pointerdown',e=>{if(e.button!==0||!e.isPrimary)return;e.preventDefault();strike();});
$('hit').addEventListener('click',e=>{if(e.detail===0)strike();});
$('hit').addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(!e.repeat)strike();}});
document.addEventListener('keydown',e=>{if(e.code==='Escape'){pause();return;}if(e.code==='Space'&&state==='playing'&&e.target.tagName!=='BUTTON'){e.preventDefault();if(!e.repeat)strike();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);
function text(s,x,y,size=12,color='#716b7b',align='center'){ctx.font=`${size>=18?'bold ':''}${size}px Arial`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(s,x,y);}
function box(x,y,bw,bh,fill,stroke='#d4cddd',radius=8){ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(x,y,bw,bh,radius);ctx.fill();ctx.stroke();}
function person(x,y,dev){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#30283e';ctx.lineWidth=2;
 if(dev){box(-22,-6,44,45,'#e8dcff','#30283e',12);ctx.fillStyle='#f6d0b1';ctx.beginPath();ctx.arc(0,-25,19,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#453248';ctx.beginPath();ctx.ellipse(-3,-40,19,9,-.22,Math.PI,Math.PI*2);ctx.fill();text('• •',0,-25,14,'#30283e');box(-29,5,58,29,'#fffdf8','#30283e',4);text('</>',0,25,15,'#7554d6');box(-42,37,84,6,'#c5b4d6');ctx.fillRect(-34,44,4,16);ctx.fillRect(30,44,4,16);box(33,15,12,17,'#d8ec9e');ctx.restore();return;}
 // Long chestnut hair, structured blue shirt and angular glasses.
 ctx.scale(1.12,1.12);ctx.fillStyle='#513629';ctx.beginPath();ctx.moveTo(-27,22);ctx.bezierCurveTo(-34,-5,-30,-49,-11,-55);ctx.bezierCurveTo(12,-65,33,-45,28,-12);ctx.lineTo(33,25);ctx.closePath();ctx.fill();ctx.stroke();
 box(-22,-1,45,37,'#287393','#253f56',8);
 ctx.fillStyle='#f2c6a6';ctx.beginPath();ctx.moveTo(-7,-9);ctx.lineTo(8,-9);ctx.lineTo(8,4);ctx.lineTo(0,11);ctx.lineTo(-8,3);ctx.closePath();ctx.fill();
 ctx.beginPath();ctx.ellipse(0,-29,19,24,.08,0,Math.PI*2);ctx.fill();ctx.stroke();
 ctx.fillStyle='#513629';ctx.beginPath();ctx.moveTo(-23,-24);ctx.bezierCurveTo(-26,-57,12,-62,24,-39);ctx.bezierCurveTo(9,-42,9,-49,5,-49);ctx.bezierCurveTo(-5,-39,-12,-35,-23,-24);ctx.fill();
 ctx.strokeStyle='#8e6645';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(-25,15);ctx.bezierCurveTo(-31,-30,-18,-50,1,-53);ctx.moveTo(18,-43);ctx.bezierCurveTo(29,-18,18,4,27,22);ctx.stroke();
 ctx.strokeStyle='#3a2c32';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-16,-37);ctx.lineTo(-5,-34);ctx.moveTo(5,-34);ctx.lineTo(16,-37);ctx.stroke();
 for(const dx of [-10,10]){box(dx-8,-33,16,13,'#d2eff044','#243c69',5);ctx.fillStyle='#403128';ctx.beginPath();ctx.arc(dx+1,-27,2.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#8cbdcb';ctx.beginPath();ctx.moveTo(dx-5,-22);ctx.lineTo(dx+3,-22);ctx.stroke();}
 ctx.strokeStyle='#243c69';ctx.beginPath();ctx.moveTo(-2,-29);ctx.lineTo(2,-29);ctx.stroke();
 ctx.strokeStyle='#ae3654';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(-5,-14);ctx.quadraticCurveTo(1,game.mood==='happy'&&game.time<game.moodUntil?-10:-14,6,-15);ctx.stroke();
 ctx.fillStyle='#429bb4';ctx.beginPath();ctx.moveTo(-9,-2);ctx.lineTo(0,10);ctx.lineTo(-11,13);ctx.lineTo(-18,1);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(9,-2);ctx.lineTo(0,10);ctx.lineTo(11,13);ctx.lineTo(18,1);ctx.closePath();ctx.fill();ctx.strokeStyle='#17445f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,11);ctx.lineTo(0,35);ctx.stroke();text('QA',12,27,8,'#bde9f2');
 box(20,8,14,9,'#246a86','#253f56',3);box(30,8,9,9,'#f2c6a6','#513629',4);
 // Baseball bat: broad barrel tapers into a thin wrapped handle and end knob.
 ctx.save();ctx.translate(35,12);ctx.rotate(game.swing>0?1.05:.35);ctx.fillStyle='#cba16d';ctx.strokeStyle='#513b2d';ctx.lineWidth=1.7;ctx.beginPath();ctx.moveTo(-3,4);ctx.lineTo(-3,-18);ctx.bezierCurveTo(-4,-30,-11,-41,-10,-67);ctx.quadraticCurveTo(0,-77,10,-67);ctx.bezierCurveTo(11,-41,4,-30,3,-18);ctx.lineTo(3,4);ctx.closePath();ctx.fill();ctx.stroke();box(-3,-16,6,20,'#323146','#30283e',2);for(let j=-13;j<4;j+=5){ctx.strokeStyle='#8e85a0';ctx.beginPath();ctx.moveTo(-3,j);ctx.lineTo(3,j-2);ctx.stroke();}box(-5,3,10,4,'#cba16d','#513b2d',2);ctx.restore();
 ctx.restore();}
function office(){const mobile=w<600;ctx.save();ctx.globalAlpha=.7;
 const bx=mobile?15:35,by=mobile?130:95,bw=mobile?108:180;
 box(bx,by,bw,87,'#f4f0e8','#ded6cc');text('СПРИНТ / ГОТОВО',bx+bw/2,by+16,9,'#9b919c');
 for(let i=0;i<6;i++){const done=i<Math.floor(game.delivered/20*6);box(bx+10+(i%3)*(bw-20)/3,by+27+Math.floor(i/3)*24,(bw-30)/3,18,done?'#d5e7ae':'#e3d9ed','#ded6cc',2);if(done)text('✓',bx+20+(i%3)*(bw-20)/3,by+40,10,'#829459');}
 if(!mobile){ctx.strokeStyle='#d8d0dd';ctx.beginPath();ctx.arc(w*.68,110,22,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(w*.68,110);ctx.lineTo(w*.68+Math.sin(game.time/12)*14,110-Math.cos(game.time/12)*14);ctx.stroke();text('ДО ДЕМО',w*.68,147,8,'#a195aa');}
 const px=w-34,py=h-34;box(px-13,py-25,26,26,'#e3d5c3','#cec2b9',4);ctx.strokeStyle='#a4b28e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(px,py-25);ctx.lineTo(px,py-75);ctx.stroke();ctx.fillStyle='#c3d0b0';for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(px+(i%2?8:-8),py-37-i*10,12,5,i%2?-.6:.6,0,Math.PI*2);ctx.fill();}
 for(let i=0;i<Math.min(5,Math.floor(game.delivered/4));i++){box(155+i*22,h-29,19,17,'#dce7be','#b5c49c',3);text('★',164+i*22,h-17,10,'#8b9d60');}
 ctx.restore();}
function visit(){if(game.time>=55&&game.time<61){const mobile=w<600,bw=Math.min(w-28,530),bx=(w-bw)/2;const pulse=matchMedia('(prefers-reduced-motion: reduce)').matches?0:(Math.sin(game.time*Math.PI*2)+1)/2;
 box(bx,8,bw,85,pulse>.5?'#ffe09a':'#ffd3a3','#cc6745',12);text('ТИМЛИД  /  ДО РЕЛИЗА '+Math.ceil(75-game.time)+' СЕК.',w/2,28,10,'#8c392d');text('СРОКИ ПОДЖИМАЮТ!',w/2,53,mobile?18:24,'#8c2e31');text(game.time<58?'Аврал через '+Math.ceil(58-game.time)+'… Приготовься!':'АВРАЛ! Держим темп, спасаем прод!',w/2,76,mobile?11:13,'#8c392d');return;}if(!game.visitor)return;const v=game.visitor,mobile=w<600,bw=Math.min(w-28,440),bx=mobile?14:w/2-bw/2,by=10;
 box(bx,by,bw,70,'#fffdf8','#c8b6e7',12);ctx.fillStyle=v.role==='ТИМЛИД'?'#d9ed98':'#e6dafa';ctx.beginPath();ctx.arc(bx+29,by+34,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f6d0b1';ctx.strokeStyle='#62506b';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(bx+29,by+34,12,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#62506b';ctx.beginPath();ctx.ellipse(bx+29,by+25,13,5,-.15,Math.PI,Math.PI*2);ctx.fill();text(v.role==='ТИМЛИД'?'⌐⌐':'• •',bx+29,by+36,11,'#62506b');ctx.beginPath();ctx.arc(bx+29,by+36,5,.3,Math.PI-.3);ctx.stroke();text(v.role,bx+57,by+17,8,'#7554d6','left');text(v.line,bx+57,by+35,mobile?10:12,'#342b43','left');const hint=v.hint.startsWith('Через 3 секунды')?(game.time<v.at+3?v.hint.replace('3 секунды',Math.ceil(v.at+3-game.time)+' сек.'):'Уже в работе — держись!'):v.hint;text(hint,bx+57,by+54,10,'#83728f','left');}
function bug(x,y,kind,returning){const color={critical:'#eb646b',medium:'#6c9fdf',minor:'#90b957'}[kind],r=kind==='critical'?14:kind==='medium'?12:10;ctx.save();ctx.translate(x,y);ctx.strokeStyle='#332b42';ctx.lineWidth=1.7;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(-r+2,i*6);ctx.lineTo(-r-5,i*8-2);ctx.moveTo(r-2,i*6);ctx.lineTo(r+5,i*8-2);ctx.stroke();}ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,0,r,r+3,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(0,r);ctx.stroke();ctx.fillStyle='#332b42';ctx.beginPath();ctx.arc(0,-r-2,6,0,Math.PI*2);ctx.fill();for(const dx of [-5,5]){ctx.beginPath();ctx.arc(dx,0,2,0,Math.PI*2);ctx.fill();}if(returning)text('↩',0,-24,15,'#7554d6');ctx.restore();}
function draw(){ctx.clearRect(0,0,w,h);office();const from={x:w-65,y:w<600?163:135},to={x:72,y:h-82};const point=p=>({x:from.x+(to.x-from.x)*p,y:from.y+(to.y-from.y)*p});ctx.strokeStyle='#e8e1f1';ctx.lineWidth=48;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.strokeStyle='#cfc3e2';ctx.lineWidth=1.5;ctx.setLineDash([4,9]);ctx.stroke();ctx.setLineDash([]);const a=point(game.hitStart),b=point(game.hitEnd);ctx.strokeStyle=game.swing>0?'#b6d57b':'#c5aff4';ctx.lineWidth=51;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();text('ЗОНА УДАРА',Math.max(62,a.x-12),a.y-40,9,'#7554d6');
 ctx.save();ctx.globalAlpha=.35;if(w>600)text('// works on my machine',w*.67,h-50,10,'#93849f');ctx.restore();person(from.x,from.y-12,true);text('РАЗРАБОТЧИК',from.x,from.y+40,9);person(to.x-12,to.y+15,false);text('МАМА · QA',to.x-12,to.y+66,9);
 for(const e of game.entities){if(e.direction===0)continue;const p=point(e.p);if(e.direction===1&&game.time>25){const tail=point(Math.max(0,e.p-.045));ctx.strokeStyle=game.time>=58?'#d697ad80':'#b4a1d570';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(tail.x,tail.y);ctx.lineTo(p.x,p.y);ctx.stroke();}if(e.kind==='feature'){if(e.special){ctx.strokeStyle='#e6c86c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.stroke();}text('★',p.x,p.y+10,31,'#e5b332');ctx.strokeStyle='#b68718';}else bug(p.x,p.y,e.kind,e.direction===-1||e.returns>0);}
 if(game.swing>0){const p=point((game.hitStart+game.hitEnd)/2);ctx.strokeStyle='#a286d7';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,33,-1.5,.7);ctx.stroke();}
 for(const e of game.effects){const age=(game.time-e.at)/.7,p=point(Math.min(e.p,.94));ctx.save();ctx.globalAlpha=1-age;const good=e.type==='hit'||e.type==='feature';for(let i=0;i<6;i++){const angle=i*Math.PI/3;ctx.fillStyle=good?'#9dbb69':'#dd858a';ctx.fillRect(p.x+Math.cos(angle)*(12+age*32),p.y+Math.sin(angle)*(12+age*32),4,4);}text(e.type==='hit'?'Баг воспроизведён!':e.type==='feature'?'+1 фича':'Ой!',p.x+25,p.y-28-age*22,11,good?'#705099':'#bd5664');ctx.restore();}
 text(game.phase.toUpperCase(),w<600?16:w/2,w<600?104:h-12,9,'#97869f',w<600?'left':'center');if(game.combo>=3){box(w-128,h-84,111,27,'#edf3dc','#c7d5ac',12);text('СЕРИЯ × '+game.combo,w-72,h-66,12,'#68833f');}visit();}
function frame(now){if(state==='playing'){if(last)accumulator+=Math.min((now-last)/1000,.1);while(accumulator>=1/120&&state==='playing'){game.step(1/120);accumulator-=1/120;for(const event of game.events){if(event.type==='hit')feedback('Баг отправлен на доработку ↗');if(event.type==='lost')feedback('Ой! Фичу потеряли. Звёзды нужно пропускать.');if(event.type==='return')feedback('«У меня всё работает!» Баг вернулся ↩');if(event.type==='miss')feedback(event.kind==='critical'?'Критичный баг в проде! Спасай остальные фичи.':'Баг проскочил в прод.');if(event.type==='feature')feedback('Фича в релизе. Так держать!');if(event.type==='end')finish();}game.events=[];}if(game.time>noticeUntil)$('feedback').textContent='Бей жуков в фиолетовой зоне. Звёзды пропускай.';hud();}last=now;draw();requestAnimationFrame(frame);}
new ResizeObserver(resize).observe(canvas);resize();requestAnimationFrame(frame);
